export { default as Tabs } from "./Tabs.vue"
export { default as Tab } from "./Tab.vue"
export { default as TabsBar } from "./TabsBar.vue"
export { default as TabsBarItem } from "./TabsBarItem.vue"
export { default as TabsContainer } from "./TabsContainer.vue"
